### ISSUE TITLE
Will changing the device affect performance?

### ISSUE THREAD

**Issue by songhat** [notmahi/dobb-e#10]
If I use the realsense camera to fine-tune, will the effect be much worse? As far as I know, it has imu and depth functions. However, I don't have an iPhone pro. @notmahi

**Comment by notmahi** [comment]
I @songhat , in our experience it should be possible, but since iPhone has a much better low-light camera, the performance might be lower with the Intel realsense camera. You can see figure 16 from our paper to see how it may matter.

<img width="683" alt="image" src="https://github.com/notmahi/dobb-e/assets/3000253/5cfc6f77-a6f6-4986-96c7-9a5bde7ac728">
